# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_code', models.CharField(max_length=9)),
            ],
        ),
        migrations.AlterModelOptions(
            name='bookholding',
            options={'ordering': ('book_instance', 'time')},
        ),
        migrations.AlterField(
            model_name='bookholding',
            name='book_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='core.BookInstance'),
        ),
        migrations.AlterField(
            model_name='bookowning',
            name='book_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownings', to='core.BookInstance'),
        ),
    ]
