# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170710_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcode',
            name='book_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BookBatch'),
        ),
    ]
