# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170712_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookowning',
            name='message',
            field=models.CharField(default='', max_length=140),
        ),
    ]
