# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170712_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookowning',
            name='message',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
    ]
