# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170710_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcode',
            name='book_batch',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.BookBatch'),
        ),
        migrations.AlterField(
            model_name='bookcode',
            name='book_code',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
