# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170714_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookholding',
            name='message',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
    ]
