# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170714_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookowning',
            name='secondary',
            field=models.BooleanField(default=False),
        ),
    ]
