# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-08 12:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20171008_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='holder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
